# version: '3.8'

services:
  php-app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-app
    hostname: php-app.ferreteria.local
    ports:
      - "${PHP_HOST_PORT:-8080}:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      ferreteria-lab-net:
        ipv4_address: 172.20.0.10
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:5.7.44
    container_name: mysql-db
    hostname: db.ferreteria.local
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      ferreteria-lab-net:
        ipv4_address: 172.20.0.11
    # NO exponemos puertos al host (ni siquiera el 3306)
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kali:
    build:
      context: ./kali
      dockerfile: Dockerfile
    container_name: kali-tools
    hostname: kali.ferreteria.local
    cap_add:
      - NET_RAW
      - NET_ADMIN    
    networks:
      ferreteria-lab-net:
        ipv4_address: 172.20.0.12
    depends_on:
      - php-app
    restart: unless-stopped


  windows-xp:
    image: dockurr/windows
    container_name: winxp-victim
    hostname: winxp.ferreteria.local
    environment:
      - VERSION=winxp
      - RAM_SIZE=1G
      - CPU_CORES=1
      - KVM=N
    #devices:
    #  - /dev/kvm # Crucial para el rendimiento (aceleraci√≥n por hardware)
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006" # Interfaz Web (VNC)
      - "3389:3389" # Acceso por Escritorio Remoto (RDP)
    volumes:
      - ./data/winxp:/storage # Para persistir el disco duro virtual
    networks:
      ferreteria-lab-net:
        ipv4_address: 172.20.0.13
    restart: unless-stopped



networks:
  ferreteria-lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24